// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: locker_user.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createLockerUser = `-- name: CreateLockerUser :execresult
INSERT INTO locker_user (user_id, locker_id) VALUES (?, ?)
`

type CreateLockerUserParams struct {
	UserID   int32 `json:"userID"`
	LockerID int32 `json:"lockerID"`
}

func (q *Queries) CreateLockerUser(ctx context.Context, arg CreateLockerUserParams) (sql.Result, error) {
	return q.exec(ctx, q.createLockerUserStmt, createLockerUser, arg.UserID, arg.LockerID)
}

const deleteLockerUser = `-- name: DeleteLockerUser :exec
DELETE FROM locker_user WHERE id = ?
`

func (q *Queries) DeleteLockerUser(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteLockerUserStmt, deleteLockerUser, id)
	return err
}

const getLockerUser = `-- name: GetLockerUser :one
SELECT id, user_id, locker_id, created_at, last_modified FROM locker_user WHERE id = ?
`

func (q *Queries) GetLockerUser(ctx context.Context, id int32) (LockerUser, error) {
	row := q.queryRow(ctx, q.getLockerUserStmt, getLockerUser, id)
	var i LockerUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LockerID,
		&i.CreatedAt,
		&i.LastModified,
	)
	return i, err
}

const updateLockerUser = `-- name: UpdateLockerUser :execresult
UPDATE locker_user SET user_id = ?, locker_id = ? WHERE id = ?
`

type UpdateLockerUserParams struct {
	UserID   int32 `json:"userID"`
	LockerID int32 `json:"lockerID"`
	ID       int32 `json:"id"`
}

func (q *Queries) UpdateLockerUser(ctx context.Context, arg UpdateLockerUserParams) (sql.Result, error) {
	return q.exec(ctx, q.updateLockerUserStmt, updateLockerUser, arg.UserID, arg.LockerID, arg.ID)
}
