// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateLocker(ctx context.Context, arg CreateLockerParams) (sql.Result, error)
	CreateLockerUser(ctx context.Context, arg CreateLockerUserParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteLocker(ctx context.Context, id int32) error
	DeleteLockerUser(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAllSensors(ctx context.Context) ([]GetAllSensorsRow, error)
	GetLocker(ctx context.Context, id int32) (GetLockerRow, error)
	GetLockerByLockerNumber(ctx context.Context, lockerNumber int32) (Locker, error)
	GetLockerByLockerNumberAndLocation(ctx context.Context, arg GetLockerByLockerNumberAndLocationParams) (Locker, error)
	GetLockerByNfcSig(ctx context.Context, nfcSig string) (int32, error)
	GetLockersOfUser(ctx context.Context, userID int32) ([]int32, error)
	GetSensorById(ctx context.Context, id int32) (GetSensorByIdRow, error)
	GetSensorsByType(ctx context.Context, kind SensorsKind) ([]GetSensorsByTypeRow, error)
	GetSensorsOfLocker(ctx context.Context, lockerID int32) ([]int32, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	UpdateLocker(ctx context.Context, arg UpdateLockerParams) (sql.Result, error)
	UpdateLockerNfcSig(ctx context.Context, arg UpdateLockerNfcSigParams) (sql.Result, error)
	UpdateLockerStatus(ctx context.Context, arg UpdateLockerStatusParams) (sql.Result, error)
	UpdateLockerUser(ctx context.Context, arg UpdateLockerUserParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
