// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateLocker(ctx context.Context) (sql.Result, error)
	CreateLockerUser(ctx context.Context) (sql.Result, error)
	CreateUser(ctx context.Context) (sql.Result, error)
	DeleteLocker(ctx context.Context) error
	DeleteLockerUser(ctx context.Context) error
	DeleteUser(ctx context.Context) error
	GetLocker(ctx context.Context) (Locker, error)
	GetLockerByLockerNumber(ctx context.Context) (Locker, error)
	GetLockerByLockerNumberAndLocation(ctx context.Context) (Locker, error)
	GetLockerByNfcSig(ctx context.Context) (Locker, error)
	GetLockerUser(ctx context.Context) (LockerUser, error)
	GetUser(ctx context.Context) (User, error)
	UpdateLocker(ctx context.Context) (sql.Result, error)
	UpdateLockerNfcSig(ctx context.Context) (sql.Result, error)
	UpdateLockerStatus(ctx context.Context) (sql.Result, error)
	UpdateLockerUser(ctx context.Context) (sql.Result, error)
	UpdateUser(ctx context.Context) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
