// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: sensors.sql

package sqlc

import (
	"context"
)

const getSensorById = `-- name: GetSensorById :one
SELECT feed_key, type FROM sensors WHERE id = ?
`

type GetSensorByIdRow struct {
	FeedKey string      `json:"feedKey"`
	Type    SensorsType `json:"type"`
}

func (q *Queries) GetSensorById(ctx context.Context, id int32) (GetSensorByIdRow, error) {
	row := q.queryRow(ctx, q.getSensorByIdStmt, getSensorById, id)
	var i GetSensorByIdRow
	err := row.Scan(&i.FeedKey, &i.Type)
	return i, err
}
